export type Skill = {
  archery: number
  crossbow: number
  tolerance: number
  smallBlades: number
  largeBlades: number
  fencing: number
  staffs: number
  warArt: number
  athletics: number
  acting: number
  stealth: number
  theft: number
  brawl: number
  riding: number
  navigation: number
  intimidate: number
  aim: number
  persuade: number
  observe: number
  seduce: number
  history: number
  acrobatics: number
  arcanism: number
  alchemy: number
  spellcasting: number
  magicResistance: number
  religion: number
  nature: number
  medicine: number
  gambling: number
}
